HospitalManagementSystem/Models/ErrorViewModel.cs
namespace HospitalManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HospitalManagementSystem/Controllers/DoctorController.cs
using Entities.Entities;
using IPBLL.Services;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem.Controllers
{
    public class DoctorController : Controller
    {
        readonly DoctorService doctorService = new DoctorService();

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterDoctor([FromBody] Doctor doctor)
        {
            var result = doctorService.AddDoctor(doctor);
            return Json(result);
        }
    }
}

HospitalManagementSystem/Controllers/HomeController.cs
using HospitalManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HospitalManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HospitalManagementSystem/Controllers/PatientController.cs
using Entities.ViewModels;
using IPBLL.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HospitalManagementSystem.Controllers
{
    public class PatientController : Controller
    {

       PatientService patientService = new PatientService();
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetPatients()
        {
            var patients = patientService.GetPatientsAppointmentsVMs();
            return Json(patients);
        }

        
        [HttpGet]
        public IActionResult GetPatientById(int id)
        {
            var patient = patientService.GetPatientsAppointmentsVMs().Where(p => p.PatientId == id).FirstOrDefault();

            return Json(patient);
        }
         
        [HttpPost]
        public async Task<IActionResult> RegisterPatient([FromBody] PatientsAppointmentsVM patient)
        {
            // Log the weight of the patient as JSON to the console
            Console.WriteLine(JsonConvert.SerializeObject(patient.Weight));

            // Call the patientService to add the patient
            var result = patientService.AddPatient(patient);

            // Return the result as JSON
            return Json(result);
        }


        [HttpPost]
        public IActionResult UpdatePatient([FromBody] PatientsAppointmentsVM patient)
        {
            var result = patientService.UpdatePatient(patient);
            return Json(result);
        }
 
        [HttpPost]
        public IActionResult DeletePatient(int id)
        {
            var result = patientService.DeletePatient(id);
            return Json(result);
        }


    }
}

HospitalManagementSystem/Views/Doctor/Index.cshtml
@{
    ViewBag.Title = "Doctor";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script type="text/javascript">

    /// <summary>
    /// Load data from the database when the page is ready
    /// </summary>
    $(document).ready(function () {
        // Load data from the database when the page is ready
        loadData();

        //Event handler for delete confirmation button click
        $('#btnConfirmDelete').click(function () {
            let doctorId = $(this).data('doctorId');

            //Ajax call to delete the doctor based on its ID from database
            $.ajax({
                url: "/Doctor/DeleteDoctor/" + doctorId,
                type: "POST",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                sucess: function (result) {
                    if (result == true) {
                        loadData();
                    }
                    else {
                        if (result == false) {
                            alert("Doctor could not be deleted");
                        }
                        else {
                            alert("An error occurred while deleting the doctor");
                        }
                    }
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });

            //Close the delete confirmation modal
            $('#deleteModal').modal('hide');
        });
    });

    /// <summary>
    /// Load data from the database
    /// </summary>
    function loadData() {
        $.ajax({
            url: "/Doctor/GetDoctors",
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                let html = '';
                $.each



</script>

HospitalManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/index.css" />

<div class="text-center">
    <h1>Book An Appointment</h1>
    <form id="patientForm" asp-controller="Patient" asp-action="RegisterPatient" method="post">
        <div class="form-elements">

            <div class="form-field">
                <label for="name" >Name:</label>
                <input type="text" id="name" name="name"  />
            </div>

            <div class="form-field">
                <label for="dob">DOB:</label>
                <input type="date" id="dob" name="dob" />
            </div>

            <div class="form-field">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" />
            </div>

            <div class="form-field">
                <label for="phone">Phone:</label>
                <input type="number" id="phone" name="phone" />
            </div>

            <div class="form-field">
                <label for="blood-group">Blood Group:  </label>
                <input type="text" id="blood-group" name="blood-group" list="blood-groups">
                <datalist id="blood-groups">
                  <option value="A+" />
                  <option value="A-" />
                  <option value="B+" />
                  <option value="B-" />
                  <option value="AB+" />
                  <option value="AB-" />
                  <option value="O+" />
                  <option value="O-" />
                </datalist>
            </div>

            <div class="form-field">
                <label for="weight">Weight:  </label>
                <input type="number" id="weight" name="weight" />
            </div>

            <div class="form-field">
                <label for="height">Height:  </label>
                <input type="number" id="height" name="height" />
            </div>

            <div class="form-field">
                <label for="doctor">Doctor: </label>
                <input type="text" id="doctor" list="doctors">
                <datalist id="doctors">
                  <option value="James" />
                  <option value="Charlie" />
                  <option value="Katie" />
                  <option value="Harman" />
                </datalist>
            </div>

            <div class="form-field">
                <label for="date">Appointment Date:  </label>
                <input type="date" id="date" name="date" />
            </div>

            <div>
                <button type="submit">Submit</button>
            </div>

        </div>
        
        
    </form>
</div>

<script>
    document.getElementById("patientForm").addEventListener("submit", function (event) {
        event.preventDefault(); // Prevent default form submission behavior

        // Serialize form data into JSON
        var formData = {};
        var formElements = this.elements;
        for (var i = 0; i < formElements.length; i++) {
            var element = formElements[i];
            if (element.tagName.toLowerCase() !== "button" && element.name) {
                formData[element.name] = element.value;
            }
        }

        // Send AJAX POST request
        fetch(this.action, {
            method: this.method,
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(formData)
        })
            .then(response => response.json())
            .then(data => {
                // Handle response from server
                console.log(data);
                // Optionally, perform any client-side actions based on the response
            })
            .catch(error => {
                console.error("Error:", error);
            });
    });
</script>

HospitalManagementSystem/Views/Patient/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<h2>Index</h2>

<style>
    .product-row {
        background-color: #f2f2f2; /* Light gray background color */
        /* Border bottom with a darker shade */
    }

        .product-row:hover {
            background-color: #d4ebe7; /* Hover effect with slightly darker background */
        }

    .product-rowh {
        background-color: #e6e6ff; /* Light gray background color */
        /* Border bottom with a darker shade */
    }

    #modal-css {
        background-color: #e6e6ff;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        loadData();
    })

    function loadData() {

        $.ajax({

            url: "/Patient/GetPatients",
            type: "GET",
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                var html = '';
                $.each(response, function (key, item) {
                    html += '<tr class = "product-row" >',
                        html += '<td>' + item.Name + '</td>';
                    html += '<td>' + item.Email + '</td>';
                    html += '<td>' + item.Phone + '</td>';
                    html += '<td>' + new Date(parseInt(item.DateOfBirth.substr(6))).toLocaleDateString() + '</td>';
                    html += '<td>' + item.BloodGroup + '</td>';
                    html += '<td>' + item.Weight + '</td>';
                    html += '<td>' + item.Height + '</td>';

        
                    //html += '<td>' + new Date(parseInt(item.EndDate.substr(6))).toLocaleDateString() + '</td>';
                    html += '<td><button type="button" class="btn btn-primary" onclick="return getPatientById(' + item.patientId + ')">Edit Patient</button>';
                    html += ' <button type="button" class="btn btn-danger" onclick="return Delete(' + item.patientId + ')">Delete Patient</button></td>';

                    html += '</tr>'
                });
                $('.tbody').html(html);
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }

        })
    }

    // function validateProductForm() {
    //     var Name = $('#name').val();
    //     var Email = $('#email').val();
    //     var Phone = $('#phone').val();
    //     var  DateOfBirth  = $('#dob').val();
    //     var BloodGroup = $('#bloodgroup').val();
    //     var Weight = $('#weight').val();
    //     var Height = $('#height').val();
    //     Validate each field
    //     if (name.trim() == '' || email.trim() == '' || phone.trim() == '' || dob.trim() == '' || bloodgroup.trim() == '' || weight.trim() == '' || height.trim() == '') {
    //         $('#errorMessage').text('All fields are required.');
    //         return false;
    //     }

    //     if (isNaN(phone)) {
    //         $('#errorMessage').text('Phone must be a number.');
    //         return false;
    //     }

    //     return true; // All validations passed
    // }



    function Add() {

        console.log("Add button clicked");
        var patientObj = {
          Name: $('#name').val(),
          Email: $('#email').val(),
          Phone: $('#phone').val(),
          DateOfBirth: $('#dob').val(),
          BloodGroup: $('#bloodgroup').val(),
          Weight: $('#weight').val(),
          Height: $('#height').val()

        }
        // if (!validateproductform()) {
        //     return false; // validation failed, abort the operation
        // }
        $.ajax({
            url: "/Patient/RegisterPatient",

            type: "POST",
            data: JSON.stringify(patientObj),

            contentType: "application/json",
            dateType: "json",
            success: function (response) {
                console.log(response);
                if (response == true) {
                    loadData();
                    $('#myModal').modal('hide');
                    $('.modal-backdrop').remove();
                }
                else {
                    $('#errorMessage').text('  an error occured ');
                }


            },
            error: function (errormessage) {
                alert(errormessage.responseText);

            }
        })
    }

    function getPatientById(patientId) {

        $.ajax({
            url: "/Patient/GetPatientById/" + patientId,
            type: "GET",
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                $('#patientId').val(response.patientId);
                $('#userId').val(result.userId);
                $('#name').val(response.Name);
                $('#email').val(response.Email);
                $('#phone').val(response.Phone);
                var DateOfBirth = new Date(parseInt(response.DateOfBirth.substr(6))).toISOString().split('T')[0]; 
            
                $('#bloodgroup').val(response.BloodGroup);
                $('#weight').val(response.Weight);
                $('#height').val(response.Height);

                $('#myModal').modal('show');
                $('#btnUpdate').show();
                $('#btnAdd').hide();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);

            },


        })
    }

    function update() {

        var patientObj = { 
            UserId: Number($('#userId').val()),
            PatientId: $('#patientId').val(),
            Name: $('#name').val(),
            Email: $('#email').val(),
            Phone: $('#phone').val(),
            DateOfBirth: $('#dob').val(),
            BloodGroup: $('#bloodgroup').val(),
            Weight: $('#weight').val(),
            Height: $('#height').val()

        }


        // if (!validateProductForm()) {
        //     return false; // Validation failed, abort the operation
        // }
        $.ajax({
            url: "/Patient/UpdatePatient",
            data: JSON.stringify(patientObj),
            type: "POST",
            contentType: "application/json",
            dateType: "json",
            success: function (response) {
                loadData();
                $('#myModal').modal('hide');
                $('.modal-backdrop').remove();

            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            },


        })
       

    }

    function Delete(patientId) {
        var ans = confirm('are u sure u want to delete product?');
        if (ans) {
            $.ajax({
                url: "/Patient/DeletePatient/",
                data: JSON.stringify({ patientId: patientId }),
                type: "POST",
                contentType: "application/json",
                dateType: "json",
                success: function (response) {
                    loadData();

                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }

            })
        }
    }

    function clearTextBoxes() {
        $('#patientId').val("");
        $('#userId').val("");
        $('#name').val("");
        $('#email').val("");
        $('#phone').val("");
        $('#dob').val("");
        $('#bloodgroup').val("");
        $('#weight').val("");
        $('#height').val("");
        $('#btnUpdate').hide();
        $('#btnAdd').show();
    }

</script>
<button type="button" class="btn btn-success btn-square" data-bs-toggle="modal" data-bs-target="#myModal" onclick="clearTextBoxes();">Add new Patient</button>

<center> <h2> Patient Registration </h2></center>

<table class="table table-bordered table-hover">
    <thead>
        <tr class="product-rowh ">
            <td>Name</td>
            <td>Email</td>
            <td>Phone</td>
            <td>DateOfBirth</td>
            <td>BloodGroup</td>
            <td>Weight</td> 
            <td>Height</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody class="tbody">
    </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class=" modal-header">
                <h4 class="modal-title">Add Patient</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-css">
                <input type="hidden" id="patientId" />

                <form>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="name" placeholder="name of patient" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="email" class="form-control" id="email" placeholder="email of patient" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="phone" placeholder="phone of patient" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="date" class="form-control" id="dob" placeholder=" date of birth" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="bloodgroup" placeholder="bloodgroup  of patient" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="weight" placeholder="weight of patient" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="height" placeholder="height of patient" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <p style="color:red" id="errorMessage"></p>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-success btn semi-circle" id="btnAdd" onclick="Add();">Add</button>
                <button type="button" class="btn btn-outline-success btn semi-circle" id="btnUpdate" onclick="update();">Update</button>
            </div>
        </div>
    </div>
</div>

HospitalManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctors Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Book an Appointment</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HospitalManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>